from __future__ import annotations

from app.apps.software_engineering.agent import default_skill_bindings
from app.platform.apps.manifest import AppManifest, AppPermissionProfile, CapabilityFlags
from app.platform.apps.profiles import AppCapabilityProfiles, ContextProfile, MCPProfile, MemoryProfile, RAGProfile


SOFTWARE_ENGINEERING_APP_MANIFEST = AppManifest(
    app_id="software_engineering",
    name="Software Engineering Agent",
    description="Harness-style software engineering agent for requirement-to-code and feedback-to-fix workflows.",
    runtime_kind="workflow",
    runtime_factory="software_engineering",
    capabilities=CapabilityFlags(history=True, memory=True, rag=True, mcp=True, skills=True, notes=True, streaming=True, workflow=True),
    permissions=AppPermissionProfile(
        allowed_tools=["repo_search_tool", "file_read_tool", "patch_write_tool", "command_run_tool", "dependency_tool", "note", "search"],
        allowed_mcp_servers=[],
        knowledge_scopes=["software_engineering"],
    ),
    profiles=AppCapabilityProfiles(
        default_context_profile="se.plan",
        context_profiles={
            "se.plan": ContextProfile(
                profile_id="se.plan",
                history_limit=8,
                max_tokens=3800,
                provider_order=["history", "memory", "rag", "notes"],
                memory_scope="session",
                note_scope="session",
                knowledge_scopes=["software_engineering"],
            ),
            "se.retrieve": ContextProfile(
                profile_id="se.retrieve",
                history_limit=8,
                max_tokens=3400,
                provider_order=["rag", "memory", "history", "notes"],
                memory_scope="session",
                note_scope="session",
                knowledge_scopes=["software_engineering"],
            ),
            "se.code": ContextProfile(
                profile_id="se.code",
                history_limit=8,
                max_tokens=4200,
                provider_order=["history", "memory", "rag", "notes"],
                memory_scope="session",
                note_scope="session",
                knowledge_scopes=["software_engineering"],
            ),
            "se.diagnose": ContextProfile(
                profile_id="se.diagnose",
                history_limit=8,
                max_tokens=3600,
                provider_order=["history", "memory", "notes"],
                memory_scope="session",
                note_scope="session",
                knowledge_scopes=["software_engineering"],
            ),
            "se.report": ContextProfile(
                profile_id="se.report",
                history_limit=8,
                max_tokens=3200,
                provider_order=["history", "memory", "notes"],
                memory_scope="session",
                note_scope="session",
                knowledge_scopes=["software_engineering"],
            ),
        },
        memory_profile=MemoryProfile(
            profile_id="se.memory",
            schema_id="se_task_workflow",
            enabled=True,
            write_policy="task_state_and_attempts",
            write_types=["working", "episodic", "semantic"],
            extraction_mode="hybrid",
            retrieval_scope="session",
            retrieval_limit=6,
            retrieval_types=["semantic", "episodic", "working"],
            retrieval_mode="hybrid",
            vector_backend="auto",
            graph_backend="auto",
            min_importance=0.3,
            working_limit=80,
            working_ttl_hours=72,
            episodic_ttl_days=90,
            promotion_threshold=0.72,
            semantic_threshold=0.84,
            consolidation_enabled=True,
            graph_enabled=True,
            perceptual_enabled=True,
            forgetting_enabled=True,
            conflict_strategy="confidence",
        ),
        rag_profile=RAGProfile(
            profile_id="se.knowledge",
            enabled=True,
            scopes=["software_engineering"],
            retrieval_limit=5,
            retrieval_mode="hybrid",
            citation_mode="inline",
            rerank_enabled=True,
            rerank_strategy="feature",
            rerank_top_n=12,
            allow_user_uploads=True,
            include_public=True,
            include_app_shared=True,
            include_user_private=True,
            include_session_temporary=True,
            query_rewrite_enabled=True,
            query_rewrite_mode="hybrid",
            mqe_variants=3,
            hyde_enabled=False,
            hyde_mode="model",
        ),
        mcp_profile=MCPProfile(
            profile_id="se.mcp",
            enabled=True,
            allowed_servers=[],
            allowed_tools=[],
            allowed_resources=[],
            allowed_prompts=[],
            connection_mode="shared",
        ),
        skills=default_skill_bindings(),
    ),
    tags=["software_engineering", "harness", "multi-agent", "workflow"],
)

