from __future__ import annotations

from app.platform.apps.manifest import AppManifest, AppPermissionProfile, CapabilityFlags
from app.platform.apps.profiles import AppCapabilityProfiles, ContextProfile, MCPProfile, MemoryProfile, RAGProfile, SkillBinding


DEEP_RESEARCH_APP_MANIFEST = AppManifest(
    app_id="deep_research",
    name="Deep Research",
    description="Workflow-driven research agent with planning, web search, notes, and final report generation.",
    runtime_kind="workflow",
    runtime_factory="deep_research",
    capabilities=CapabilityFlags(history=True, memory=True, rag=True, mcp=False, skills=True, notes=True, streaming=True, workflow=True),
    permissions=AppPermissionProfile(
        allowed_tools=["search", "note"],
        allowed_mcp_servers=[],
        knowledge_scopes=["deep_research"],
    ),
    profiles=AppCapabilityProfiles(
        default_context_profile="research.plan",
        context_profiles={
            "research.plan": ContextProfile(
                profile_id="research.plan",
                history_limit=10,
                max_tokens=6000,
                provider_order=["history", "memory", "rag", "notes"],
                memory_scope="session",
                note_scope="session",
                knowledge_scopes=["deep_research"],
            ),
            "research.summarize": ContextProfile(
                profile_id="research.summarize",
                history_limit=10,
                max_tokens=6000,
                provider_order=["search", "memory", "rag", "notes", "history"],
                memory_scope="session",
                note_scope="session",
                knowledge_scopes=["deep_research"],
            ),
            "research.report": ContextProfile(
                profile_id="research.report",
                history_limit=10,
                max_tokens=6000,
                provider_order=["task_summary", "memory", "rag", "notes", "history"],
                memory_scope="session",
                note_scope="session",
                knowledge_scopes=["deep_research"],
            ),
        },
        memory_profile=MemoryProfile(
            profile_id="research.memory",
            schema_id="research_workflow",
            enabled=True,
            write_policy="remember_task_findings",
            write_types=["working", "episodic", "semantic"],
            extraction_mode="hybrid",
            retrieval_scope="session",
            retrieval_limit=6,
            retrieval_types=["semantic", "episodic", "perceptual"],
            retrieval_mode="hybrid",
            vector_backend="auto",
            graph_backend="auto",
            min_importance=0.3,
            working_limit=40,
            working_ttl_hours=72,
            episodic_ttl_days=120,
            promotion_threshold=0.75,
            semantic_threshold=0.85,
            consolidation_enabled=True,
            graph_enabled=True,
            perceptual_enabled=True,
            forgetting_enabled=True,
            conflict_strategy="confidence",
        ),
        rag_profile=RAGProfile(
            profile_id="research.knowledge",
            enabled=True,
            scopes=["deep_research"],
            retrieval_limit=6,
            retrieval_mode="hybrid",
            citation_mode="inline",
            rerank_enabled=True,
            rerank_strategy="feature",
            rerank_top_n=12,
            allow_user_uploads=True,
            include_public=True,
            include_app_shared=True,
            include_user_private=True,
            include_session_temporary=True,
            query_rewrite_enabled=True,
            query_rewrite_mode="hybrid",
            mqe_variants=4,
            hyde_enabled=True,
            hyde_mode="model",
        ),
        mcp_profile=MCPProfile(
            profile_id="research.mcp",
            enabled=False,
            allowed_servers=[],
            allowed_tools=[],
            allowed_resources=[],
            allowed_prompts=[],
            connection_mode="shared",
        ),
        skills=[
            SkillBinding(skill_id="source_grounding", stage="research.summarize", priority=100),
            SkillBinding(skill_id="source_grounding", stage="research.report", priority=100),
            SkillBinding(skill_id="research_planning", stage="research.plan", priority=120),
            SkillBinding(skill_id="research_synthesis", stage="research.summarize", priority=140),
            SkillBinding(skill_id="research_synthesis", stage="research.report", priority=140),
        ],
    ),
    tags=["research", "workflow", "multi-stage"],
)
