from __future__ import annotations

from app.platform.apps.manifest import AppManifest, AppPermissionProfile, CapabilityFlags
from app.platform.apps.profiles import AppCapabilityProfiles, ContextProfile, MCPProfile, MemoryProfile, RAGProfile, SkillBinding


CHAT_APP_MANIFEST = AppManifest(
    app_id="chat",
    name="Universal Chat",
    description="General-purpose agent chat with context, memory, RAG, notes, and tool use.",
    runtime_kind="chat",
    runtime_factory="chat",
    capabilities=CapabilityFlags(history=True, memory=True, rag=True, mcp=True, skills=True, notes=True, streaming=True),
    permissions=AppPermissionProfile(
        allowed_tools=["search", "note"],
        allowed_mcp_servers=[],
        knowledge_scopes=["chat"],
    ),
    profiles=AppCapabilityProfiles(
        default_context_profile="chat.reply",
        context_profiles={
            "chat.reply": ContextProfile(
                profile_id="chat.reply",
                history_limit=10,
                max_tokens=3200,
                provider_order=["history", "memory", "rag"],
                memory_scope="user",
                note_scope="session",
                knowledge_scopes=["chat"],
            )
        },
        memory_profile=MemoryProfile(
            profile_id="chat.memory",
            schema_id="chat_user_profile",
            enabled=True,
            write_policy="remember_interactions_and_facts",
            write_types=["working", "episodic", "semantic"],
            extraction_mode="hybrid",
            retrieval_scope="user",
            retrieval_limit=2,
            retrieval_types=["semantic", "episodic"],
            retrieval_mode="lexical",
            vector_backend="auto",
            graph_backend="disabled",
            min_importance=0.2,
            working_limit=24,
            working_ttl_hours=24,
            episodic_ttl_days=60,
            promotion_threshold=0.7,
            semantic_threshold=0.82,
            consolidation_enabled=True,
            graph_enabled=False,
            perceptual_enabled=True,
            forgetting_enabled=True,
            conflict_strategy="confidence",
        ),
        rag_profile=RAGProfile(
            profile_id="chat.knowledge",
            enabled=True,
            scopes=["chat"],
            retrieval_limit=3,
            retrieval_mode="hybrid",
            citation_mode="inline",
            rerank_enabled=False,
            rerank_strategy="feature",
            rerank_top_n=10,
            allow_user_uploads=True,
            include_public=True,
            include_app_shared=True,
            include_user_private=True,
            include_session_temporary=True,
            query_rewrite_enabled=False,
            query_rewrite_mode="heuristic",
            mqe_variants=2,
            hyde_enabled=False,
            hyde_mode="model",
        ),
        mcp_profile=MCPProfile(
            profile_id="chat.mcp",
            enabled=True,
            allowed_servers=[],
            allowed_tools=[],
            allowed_resources=[],
            allowed_prompts=[],
            connection_mode="shared",
        ),
        skills=[
            SkillBinding(skill_id="general_qa", stage="chat.reply", priority=100),
            SkillBinding(skill_id="tool_use_hygiene", stage="chat.reply", priority=120),
            SkillBinding(skill_id="source_grounding", stage="chat.reply", priority=140),
        ],
    ),
    tags=["general", "assistant", "platform-entry"],
)
